version: "3"


services:

  product-api:
      build: "./product-api"
      volumes:
      - "./product-api:/app"
      ports:
      - "8080:8080"

  frontend:
     image: php:8.1-apache-buster
     volumes:
     - "./frontend:/var/www/html"
     ports:
     - "80:80"
     depends_on:
     - product-api
